import grpc
from concurrent import futures
import time
import numpy as np
import os
import sys

# Add current directory to path so generated modules can be found
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

# These will be generated by the build process
try:
    import inference_pb2
    import inference_pb2_grpc
except ImportError:
    print("Error: Protobuf files not found. Did you run code generation?")
    # We don't exit here so the file can be saved even if dependencies aren't ready
    pass

class InferenceService(inference_pb2_grpc.ModelInferenceServicer):
    def Predict(self, request, context):
        model_name = request.model_name or "unknown"
        print(f"[Inference] 🧠 Received request for model: {model_name}")
        print(f"[Inference] 🔢 Features received: {len(request.features)}")
        
        start_time = time.time()
        
        # ---------------------------------------------------------
        # THE MOCK "HEAVY" COMPUTE
        # Simulating a large Matrix Multiplication or Transformer Forward Pass
        # ---------------------------------------------------------
        time.sleep(0.5) # 500ms Latency Simulation
        
        # Mock logic
        class_id = int(np.random.randint(0, 5))
        confidence = float(np.random.uniform(0.85, 0.99))
        
        elapsed = time.time() - start_time
        print(f"[Inference] ✅ Processed in {elapsed:.4f}s")
        
        return inference_pb2.PredictResponse(
            class_id=class_id,
            confidence=confidence,
            error=""
        )

def serve():
    print("[Inference] Starting gRPC Server...")
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    inference_pb2_grpc.add_ModelInferenceServicer_to_server(InferenceService(), server)
    
    port = os.environ.get("PORT", "50051")
    server.add_insecure_port(f'[::]:{port}')
    print(f"[Inference] 🚀 Server listening on port {port}")
    server.start()
    server.wait_for_termination()

if __name__ == '__main__':
    serve()
